name: scan_system_app
description: Multi-tenant barcode scanner app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared:
    path: ../packages/shared

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.0

  # HTTP
  dio: ^5.4.0

  # Local DB
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Scanner
  mobile_scanner: ^7.1.4

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Web Audio
  web: ^1.1.0

  # Utils
  uuid: ^4.2.1
  file_picker: ^10.1.9
  excel: ^4.0.6

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
